import requests
from django.conf import settings

class MSG91SMSConnector:
    BASE_URL = settings.MSG91_OTP_API_BASE_URL
    VERIFY_URL = settings.MSG91_VERIFY_OTP_API_BASE_URL

    def __init__(self):
        self.auth_key = settings.MSG91_AUTH_KEY
        self.template_id = settings.MSG91_OTP_TEMPLATE_ID

    def send_otp(self, mobile_number):
        """
        Sends an OTP via MSG91. OTP is auto-generated by MSG91.
        :param mobile_number: Mobile number without country code
        :return: dict with API response
        """
        payload = {
            "authkey": self.auth_key,
            "mobile": f"91{mobile_number}",
            "template_id": self.template_id,
            "otp_length": 4,
            "otp_expiry": 5,  # in minutes
            "realTimeResponse": 1 
        }
        headers = {
            "Content-Type": "application/json"
        }
        try:
            response = requests.post(self.BASE_URL, headers=headers, json=payload)
            return response.json()
        except requests.RequestException as e:
            return {"error": str(e)}

    def verify_otp(self, mobile_number, otp):
        """
        Verifies the OTP via MSG91
        :param mobile_number: Mobile number without country code
        :param otp: OTP entered by user
        :return: dict with API response
        """
        payload = {
            "authkey": self.auth_key,
            "mobile": f"91{mobile_number}",
            "otp": otp
        }
        headers = {
            "Content-Type": "application/json"
        }
        try:
            response = requests.post(self.VERIFY_URL, headers=headers, json=payload)
            return response.json()
        except requests.RequestException as e:
            return {"error": str(e)}
